services:
  - type: web
    name: roleplay-chronicles
    env: python
    region: frankfurt
    python:
      version: 3.11.6
    buildCommand: |
      chmod +x setup.sh
      ./setup.sh
    startCommand: gunicorn "wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PYTHONUNBUFFERED
        value: true
      - key: PYTHONHASHSEED
        value: random
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        fromService:
          name: roleplay-chronicles
          type: web
          property: env.SUPABASE_URL
      - key: SUPABASE_KEY
        fromService:
          name: roleplay-chronicles
          type: web
          property: env.SUPABASE_KEY
      - key: DATABASE_URL
        fromService:
          name: roleplay-chronicles
          type: web
          property: env.DATABASE_URL
